INSERT INTO CURR_BLOCKS
SELECT *
FROM BLOCKS
WHERE NUMBER = {curr_update_block};

INSERT INTO CURR_TRANSACTIONS
SELECT *
FROM TRANSACTIONS
WHERE BLOCK_HASH = (
    SELECT HASH
    FROM BLOCKS
    WHERE NUMBER = {curr_update_block}
);

WITH NEWLY_CREATED_TOKENS AS (
    SELECT TOKENS.ADDRESS AS ADDRESS
    FROM CURR_BLOCKS, TOKENS
    WHERE CURR_BLOCKS.HASH = TOKENS.BLOCK_HASH
    AND CURR_BLOCKS.NUMBER = {curr_update_block}
),
NEWLY_REFERENCED_TOKENS AS (
    SELECT TOKEN_TRANSACTIONS.TOKEN_ADDRESS AS ADDRESS
    FROM CURR_BLOCKS, CURR_TRANSACTIONS, TOKEN_TRANSACTIONS
    WHERE CURR_BLOCKS.HASH = CURR_TRANSACTIONS.BLOCK_HASH
    AND CURR_TRANSACTIONS.HASH = TOKEN_TRANSACTIONS.TRANSACTION_HASH
    AND CURR_BLOCKS.NUMBER = {curr_update_block}
),
TOKENS_TO_ADD AS (
    (SELECT ADDRESS
    FROM NEWLY_CREATED_TOKENS
    EXCEPT
    SELECT ADDRESS
    FROM CURR_TOKENS)
    UNION
    (SELECT ADDRESS
    FROM NEWLY_REFERENCED_TOKENS
    EXCEPT
    SELECT ADDRESS
    FROM CURR_TOKENS)
)
INSERT INTO CURR_TOKENS
SELECT *
FROM TOKENS
WHERE ADDRESS IN (SELECT * FROM TOKENS_TO_ADD);

WITH NEW_TOKEN_TRANSACTIONS AS (
    SELECT TOKEN_TRANSACTIONS.TRANSACTION_HASH
    FROM CURR_BLOCKS, CURR_TRANSACTIONS, TOKEN_TRANSACTIONS
    WHERE CURR_BLOCKS.HASH = CURR_TRANSACTIONS.BLOCK_HASH
    AND CURR_TRANSACTIONS.HASH = TOKEN_TRANSACTIONS.TRANSACTION_HASH
    AND CURR_BLOCKS.NUMBER = {curr_update_block}
)
INSERT INTO CURR_TOKEN_TRANSACTIONS
SELECT *
FROM TOKEN_TRANSACTIONS
WHERE TRANSACTION_HASH IN (SELECT TRANSACTION_HASH FROM NEW_TOKEN_TRANSACTIONS);

WITH NEWLY_CREATED_CONTRACTS AS (
    SELECT CONTRACTS.ADDRESS AS ADDRESS
    FROM CURR_BLOCKS, CONTRACTS
    WHERE CURR_BLOCKS.HASH = CONTRACTS.BLOCK_HASH
    AND CURR_BLOCKS.NUMBER = {curr_update_block}
),
NEWLY_REFERENCED_CONTRACTS AS (
    SELECT CURR_TRANSACTIONS.TO_ADDRESS AS ADDRESS
    FROM CURR_BLOCKS, CURR_TRANSACTIONS, CONTRACTS
    WHERE CURR_BLOCKS.HASH = CURR_TRANSACTIONS.BLOCK_HASH
	AND CURR_TRANSACTIONS.TO_ADDRESS = CONTRACTS.ADDRESS
    AND CURR_BLOCKS.NUMBER = {curr_update_block}
),
CONTRACTS_TO_ADD AS (
    (SELECT ADDRESS
    FROM NEWLY_CREATED_CONTRACTS
    EXCEPT
    SELECT ADDRESS
    FROM CURR_CONTRACTS)
    UNION
    (SELECT ADDRESS
    FROM NEWLY_REFERENCED_CONTRACTS
    EXCEPT
    SELECT ADDRESS
    FROM CURR_CONTRACTS)
)
INSERT INTO CURR_CONTRACTS
SELECT *
FROM CONTRACTS
WHERE ADDRESS IN (SELECT * FROM CONTRACTS_TO_ADD);

INSERT INTO CURR_WITHDRAWALS
SELECT *
FROM WITHDRAWALS
WHERE HASH = (
    SELECT HASH
    FROM BLOCKS
    WHERE NUMBER = {curr_update_block}
);

CREATE TEMPORARY TABLE Temp_Relevant_From_Updated AS
SELECT DISTINCT from_address AS address
FROM TRANSACTIONS
JOIN BLOCKS ON TRANSACTIONS.block_hash = BLOCKS.hash
WHERE BLOCKS.number BETWEEN {curr_update_block - 999} AND {curr_update_block};

CREATE TEMPORARY TABLE Temp_Relevant_To_Updated AS
SELECT DISTINCT to_address AS address
FROM TRANSACTIONS
JOIN BLOCKS ON TRANSACTIONS.block_hash = BLOCKS.hash
WHERE BLOCKS.number BETWEEN {curr_update_block - 999} AND {curr_update_block};

CREATE TEMPORARY TABLE Temp_Relevant_Miner_Updated AS
SELECT DISTINCT miner AS address
FROM BLOCKS
WHERE number BETWEEN {curr_update_block - 999} AND {curr_update_block};

CREATE TEMPORARY TABLE Temp_Relevant_Withdrawals_Updated AS
SELECT DISTINCT withdrawals.address
FROM WITHDRAWALS
JOIN BLOCKS ON WITHDRAWALS.hash = BLOCKS.hash
WHERE BLOCKS.number BETWEEN {curr_update_block - 999} AND {curr_update_block};

CREATE TEMPORARY TABLE Temp_Contract_Addresses_Updated AS
SELECT contracts.address
FROM BLOCKS
JOIN TRANSACTIONS ON BLOCKS.hash = TRANSACTIONS.block_hash
JOIN CONTRACTS ON TRANSACTIONS.to_address = CONTRACTS.address
WHERE BLOCKS.number BETWEEN {curr_update_block - 999} AND {curr_update_block}
UNION
SELECT contracts.address
FROM CONTRACTS, BLOCKS
WHERE CONTRACTS.BLOCK_HASH = BLOCKS.HASH
AND BLOCKS.number BETWEEN {curr_update_block - 999} AND {curr_update_block};

CREATE TEMPORARY TABLE Temp_Relevant_Address_Updated AS
SELECT address FROM Temp_Relevant_From_Updated
UNION
SELECT address FROM Temp_Relevant_To_Updated
UNION
SELECT address FROM Temp_Relevant_Miner_Updated
UNION
SELECT address FROM Temp_Relevant_Withdrawals_Updated
UNION 
SELECT address FROM Temp_Contract_Addresses_Updated;

CREATE TEMPORARY TABLE Temp_Relevant_From_Current AS
SELECT DISTINCT from_address AS address
FROM TRANSACTIONS
JOIN BLOCKS ON TRANSACTIONS.block_hash = BLOCKS.hash
WHERE BLOCKS.number BETWEEN {curr_update_block - 1000} AND {curr_update_block - 1};

CREATE TEMPORARY TABLE Temp_Relevant_To_Current AS
SELECT DISTINCT to_address AS address
FROM TRANSACTIONS
JOIN BLOCKS ON TRANSACTIONS.block_hash = BLOCKS.hash
WHERE BLOCKS.number BETWEEN {curr_update_block - 1000} AND {curr_update_block - 1};

CREATE TEMPORARY TABLE Temp_Relevant_Miner_Current AS
SELECT DISTINCT miner AS address
FROM BLOCKS
WHERE number BETWEEN {curr_update_block - 1000} AND {curr_update_block - 1};

CREATE TEMPORARY TABLE Temp_Relevant_Withdrawals_Current AS
SELECT DISTINCT withdrawals.address
FROM WITHDRAWALS
JOIN BLOCKS ON WITHDRAWALS.hash = BLOCKS.hash
WHERE BLOCKS.number BETWEEN {curr_update_block - 1000} AND {curr_update_block - 1};

CREATE TEMPORARY TABLE Temp_Contract_Addresses_Current AS
SELECT contracts.address
FROM BLOCKS
JOIN TRANSACTIONS ON BLOCKS.hash = TRANSACTIONS.block_hash
JOIN CONTRACTS ON TRANSACTIONS.to_address = CONTRACTS.address
WHERE BLOCKS.number BETWEEN {curr_update_block - 1000} AND {curr_update_block - 1}
UNION
SELECT contracts.address
FROM CONTRACTS, BLOCKS
WHERE CONTRACTS.BLOCK_HASH = BLOCKS.HASH
AND BLOCKS.number BETWEEN {curr_update_block - 1000} AND {curr_update_block - 1};

CREATE TEMPORARY TABLE Temp_Relevant_Address_Current AS
SELECT address FROM Temp_Relevant_From_Current
UNION
SELECT address FROM Temp_Relevant_To_Current
UNION
SELECT address FROM Temp_Relevant_Miner_Current
UNION
SELECT address FROM Temp_Relevant_Withdrawals_Current
UNION 
SELECT address FROM Temp_Contract_Addresses_Current;

WITH ADDRESSES_TO_INSERT AS (
    SELECT * FROM Temp_Relevant_Address_Updated
    EXCEPT
    SELECT * FROM Temp_Relevant_Address_Current
)
INSERT INTO CURR_ADDRESSES
SELECT *
FROM ADDRESSES
WHERE ADDRESS IN (SELECT * FROM ADDRESSES_TO_INSERT);

WITH SentInNewBlock AS (
    SELECT from_address AS address, SUM(value) AS total_sent
    FROM CURR_TRANSACTIONS
    WHERE BLOCK_HASH = (
        SELECT HASH
        FROM BLOCKS
        WHERE NUMBER = {curr_update_block}
    )
    GROUP BY from_address
),
ReceivedInNewBlock AS (
    SELECT to_address AS address, SUM(value) AS total_received
    FROM CURR_TRANSACTIONS
    WHERE BLOCK_HASH = (
        SELECT HASH
        FROM BLOCKS
        WHERE NUMBER = {curr_update_block}
    )
    GROUP BY to_address
),
RelevantAddresses AS (
    SELECT *
    FROM CURR_ADDRESSES C
    WHERE C.ADDRESS IN (SELECT ADDRESS FROM SentInNewBlock) OR C.ADDRESS IN (SELECT ADDRESS FROM ReceivedInNewBlock)
)
UPDATE CURR_ADDRESSES
SET ETH_BALANCE = C.ETH_BALANCE + COALESCE(R.total_received, 0) - COALESCE(S.total_sent, 0)
FROM RelevantAddresses C
LEFT OUTER JOIN SentInNewBlock S ON C.ADDRESS = S.ADDRESS
LEFT OUTER JOIN ReceivedInNewBlock R ON C.ADDRESS = R.ADDRESS;

DROP TABLE IF EXISTS Temp_Relevant_From_Updated CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_To_Updated CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_Miner_Updated CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_Withdrawals_Updated CASCADE;
DROP TABLE IF EXISTS Temp_Contract_Addresses_Updated CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_Address_Updated CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_From_Current CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_To_Current CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_Miner_Current CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_Withdrawals_Current CASCADE;
DROP TABLE IF EXISTS Temp_Contract_Addresses_Current CASCADE;
DROP TABLE IF EXISTS Temp_Relevant_Address_Current CASCADE;
